config/routes.rb
Rails.application.routes.draw do

  # Dynamic error pages
  get "/400", to: "errors#bad_request"
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  apipie
  namespace :api do
    namespace :v1 do
      resources :claps, only: [:create]
      resources :saved_routes, only: [:index, :create, :destroy]
      resources :routes do
        resources :point_of_interests, only: [:create, :destroy]
        post 'point_of_interests_many', to: 'point_of_interests#create_many'
        get :export_gpx_file
      end
      get 'search', to: 'search#search'
      get 'location_search', to: 'search#location_search'
      resources :sessions, only: [:create, :destroy]
      resources :registrations, only: [:create]
      resources :users do
        resources :followed_blogs, only: [:create, :destroy, :index]
      end
      resources :conversations do
        resources :messages, only: [:index, :create, :update]
      end
      resources :trips do
        resources :posts do
          resources :post_pictures, only: [:create, :destroy]
        end
        resources :donation_goals, only: [:create, :edit]
        resources :post_groups, only: [:show, :update]
        resources :gear_lists, only: [:create, :update]
        resources :transactions, only: [:create]
        resources :poly_line_strings, only: [:index]
      end
    end
  end

  devise_for :users, :controllers => { :registrations => 'registrations', omniauth_callbacks: 'api/v1/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get "/about", to: "home#about", as: "about"
  get "/terms", to: "home#terms", as: "terms"

  resources :feedbacks, only: [:create]

  resources :users do
    resources :followed_blogs, only: [:index, :create, :destroy]
    get "verification", to: "users#verification", as: "verification"
    get "unsubscribe", to: "users#unsubscribe", as: "unsubscribe"
    patch "pardon", to: "admin#pardon", as: "pardon"
    patch "warn", to: "admin#warn", as: "warn"
    patch "ban", to: "admin#ban", as: "ban"
  end

  # admin route
  resources :admin, only: [:index]
  get "/admin/flagged_messages", to: "admin#flagged_messages", as: "flagged_messages"

  get 'search', to: 'search#search'
  get :trip_planner_search, to: "search#location_search"

  resources :trips do
    get "track_route", to: "posts#track_route", as: "track_route"
    resources :posts do
      resources :post_pictures, only: [:new, :create, :destroy]
      get "fetch_images", to: "post_pictures#fetch_images", as: "fetch_images"
    end
    get :fetch_posts
    resources :transactions, only: [:new, :create]
    resources :donation_goals, only: [:new, :create, :update, :edit]
    resources :post_groups, only: [:show, :update]
    resources :gear_lists, only: [:create, :update]
    get "fetch_post/:id", to: "post_groups#fetch_post", as: "fetch_post"
    get "fetch_post_planer/:id", to: "trip_planner#fetch_post", as: "fetch_post_planer"
  end

  resources :claps, only: [:create]
  resources :comments, only: [:create, :update, :destroy]

  resources :routes do
    resources :point_of_interests, only: [:create, :destroy]
    get :fetch_pois
    get :export_gpx_file
  end
  resources :saved_routes, only: [:index, :create, :show, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/controllers/trip_planner_controller.rb
class TripPlannerController < ApplicationController

  def show
    @trip = Trip.find(params[:id])
    @posts = @trip.posts.sort_by {|obj| obj.day}
    @post = @posts.first
    @user = @trip.user
  end

  def fetch_post
    @post = Post.find(params[:id])
    @post_pictures = @post.post_pictures
    @user = current_user
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/trip_planner_helper.rb
module TripPlannerHelper
end

app/views/trip_planner/fetch_post.js.erb
$("#post-container").html('<%= escape_javascript(render :partial => "post", :locals => { :post => @post, :post_pictures => @post_pictures, :user => @user}) %>');

app/views/trip_planner/index.html.erb
<%= javascript_include_tag "trip_planner" %>
<script
 src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAOPUyGan2qsdAXBODCGHa2TN6myWIxZFQ&libraries=geometry">
</script>
<div id="wrapper">
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand"><a href="<%= trip_path(@trip) %>">Back to trip</a></li>
      <% @posts.each_with_index do |post, index| %>
        <% if index == 0 %>
        <li class="<%="#{post.id}" %> sidebar-active-item"><a href="<%= trip_fetch_post_planer_url(@trip, post) %>" class="post-sidebar-item trip-planner-sidebar-item" data-value="<%= post.id %>" data-lat="<%= post.center_lat %>" data-lng="<%= post.center_lng %>"><%= "#{post.post_group.month} #{post.day}" %></a></li>
        <% else %>
        <li class="<%= post.id %>"><a href="<%= trip_fetch_post_planer_url(@trip, post) %>" class="post-sidebar-item trip-planner-sidebar-item" data-value="<%= post.id %>" data-lat="<%= post.center_lat %>" data-lng="<%= post.center_lng %>"><%= "#{post.post_group.month} #{post.day}" %></a></li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div id="page-content-wrapper trip-planer">
    <div class="container-fluid trip-planer">
      <div class="row">
        <div class="col-lg-12">
          <div id="map-trip-planner">

          </div>
          <div id="post-container">
            <%= render 'post' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trip_planner/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3>Found trips</h3>
    </div>
      <% @found_trips.each do |found_trip| %>
      <% trip_owner = found_trip.user %>
      <div class="col-sm-12 user-search-column">
        <div class="row">
          <div class="col-sm-3">
            <% if trip_owner.avatar_url == nil %>
                <a href="http://placehold.it" class="profile-image"><%= image_tag "missing.png", :class=> "img-thumbnail" %></a>
            <% else %>
                <%= image_tag trip_owner.avatar.thumb.url, :class => "user-cover-photo img-rounded" %>
            <% end %>
          </div>
          <div class="col-sm-3">
            <h1><%= link_to found_trip.trip_name, trip_path(found_trip) %></h1>
          </div>
          <div class="col-sm-5 col-sm-offset-1">
            <p>
              some blog stuff it would be cool if this gave a bit on the very last post the user made
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/trip_planner/show.html.erb
<%= javascript_include_tag "trip_planner" %>
<script
 src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API'] %>&libraries=geometry">
</script>
<div id="wrapper">
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand"><a href="<%= trip_path(@trip) %>">Back to trip</a></li>
      <% @posts.each_with_index do |post, index| %>
        <% if index == 0 %>
        <li class="<%="#{post.id}" %> sidebar-active-item"><a href="<%= trip_fetch_post_planer_url(@trip, post) %>" class="post-sidebar-item trip-planner-sidebar-item" data-value="<%= post.id %>" data-lat="<%= post.center_lat %>" data-lng="<%= post.center_lng %>"><%= "#{post.post_group.month} #{post.day}" %></a></li>
        <% else %>
        <li class="<%= post.id %>"><a href="<%= trip_fetch_post_planer_url(@trip, post) %>" class="post-sidebar-item trip-planner-sidebar-item" data-value="<%= post.id %>" data-lat="<%= post.center_lat %>" data-lng="<%= post.center_lng %>"><%= "#{post.post_group.month} #{post.day}" %></a></li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div id="page-content-wrapper trip-planer">
    <div class="container-fluid trip-planer">
      <div class="row">
        <div class="col-lg-12">
          <div id="map-trip-planner">

          </div>
          <div id="post-container">
            <%= render 'post' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>