config/routes.rb
Rails.application.routes.draw do

  # Dynamic error pages
  get "/400", to: "errors#bad_request"
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  apipie
  namespace :api do
    namespace :v1 do
      resources :claps, only: [:create]
      resources :saved_routes, only: [:index, :create, :destroy]
      resources :routes do
        resources :point_of_interests, only: [:create, :destroy]
        post 'point_of_interests_many', to: 'point_of_interests#create_many'
        get :export_gpx_file
      end
      get 'search', to: 'search#search'
      get 'location_search', to: 'search#location_search'
      resources :sessions, only: [:create, :destroy]
      resources :registrations, only: [:create]
      resources :users do
        resources :followed_blogs, only: [:create, :destroy, :index]
      end
      resources :conversations do
        resources :messages, only: [:index, :create, :update]
      end
      resources :trips do
        resources :posts do
          resources :post_pictures, only: [:create, :destroy]
        end
        resources :donation_goals, only: [:create, :edit]
        resources :post_groups, only: [:show, :update]
        resources :gear_lists, only: [:create, :update]
        resources :transactions, only: [:create]
        resources :poly_line_strings, only: [:index]
      end
    end
  end

  devise_for :users, :controllers => { :registrations => 'registrations', omniauth_callbacks: 'api/v1/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get "/about", to: "home#about", as: "about"
  get "/terms", to: "home#terms", as: "terms"

  resources :feedbacks, only: [:create]

  resources :users do
    resources :followed_blogs, only: [:index, :create, :destroy]
    get "verification", to: "users#verification", as: "verification"
    get "unsubscribe", to: "users#unsubscribe", as: "unsubscribe"
    patch "pardon", to: "admin#pardon", as: "pardon"
    patch "warn", to: "admin#warn", as: "warn"
    patch "ban", to: "admin#ban", as: "ban"
  end

  # admin route
  resources :admin, only: [:index]
  get "/admin/flagged_messages", to: "admin#flagged_messages", as: "flagged_messages"

  get 'search', to: 'search#search'
  get :trip_planner_search, to: "search#location_search"

  resources :trips do
    get "track_route", to: "posts#track_route", as: "track_route"
    resources :posts do
      resources :post_pictures, only: [:new, :create, :destroy]
      get "fetch_images", to: "post_pictures#fetch_images", as: "fetch_images"
    end
    get :fetch_posts
    resources :transactions, only: [:new, :create]
    resources :donation_goals, only: [:new, :create, :update, :edit]
    resources :post_groups, only: [:show, :update]
    resources :gear_lists, only: [:create, :update]
    get "fetch_post/:id", to: "post_groups#fetch_post", as: "fetch_post"
    get "fetch_post_planer/:id", to: "trip_planner#fetch_post", as: "fetch_post_planer"
  end

  resources :claps, only: [:create]
  resources :comments, only: [:create, :update, :destroy]

  resources :routes do
    resources :point_of_interests, only: [:create, :destroy]
    get :fetch_pois
    get :export_gpx_file
  end
  resources :saved_routes, only: [:index, :create, :show, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/views/admin/flagged_messages.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <table class="table">
        <tr>
          <th>Username</th>
          <th>Message Content</th>
          <th>User Offense Count</th>
          <th>Pardon User</th>
          <th>Warn User</th>
          <th>Ban User</th>
        </tr>
        <% @flagged_messages.each do |flagged_message| %>
          <% user = flagged_message.user %>
          <% if flagged_message.open_offense %>
          <tr>
            <td><%= user.name %></td>
            <td><%= flagged_message.body %></td>
            <td><%= user.offense_count %></td>
            <td><%= button_to('Pardon User', user_pardon_path(user.id, message_id: flagged_message.id), :class => 'btn btn-success', :method => :patch) %></td>
            <td><%= button_to('Warn User', user_warn_path(user.id, message_id: flagged_message.id), :class => 'btn btn-warning', :method => :patch) %></td>
            <td><%= button_to('Ban User', user_ban_path(user.id, message_id: flagged_message.id), :class => 'btn btn-danger btn-ban-user', :method => :patch) %></td>
          </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <a href="/admin/flagged_messages" class="btn btn-primary go-to-flagged-messages">Go to flagged messages</a>
    </div>
    <div class="col-sm-4 well text-center">
      <i class="fa fa-user-circle fa-5x"></i>
      <p><%= @users.length %> users</p>
    </div>
    <div class="col-sm-4 well text-center">
      <i class="fa fa-book fa-5x"></i>
      <p><%= @posts.length %> posts</p>
    </div>
    <div class="col-sm-4 well text-center">
      <i class="fa fa-money fa-5x"></i>
      <p><%= @total_raised %>$ raised</p>
    </div>
    <div class="col-sm-12 well">
      <p>Cumulative Sign up</p>
      <% sum = 0 %>
      <%= line_chart @users.group_by_week(:created_at).count.map { |x,y| { x => (sum += y)} }.reduce({}, :merge) %>
    </div>
    <div class="col-sm-12 well">
      <p>Sign in count (note does not track returning peoples)</p>
      <%= line_chart User.group_by_day(:last_sign_in_at).count %>
    </div>
    <div class="col-sm-12 well">
      <p>New Posts</p>
      <%= line_chart @posts.group_by_day(:created_at).count %>
    </div>
  </div>
</div>