config/routes.rb
Rails.application.routes.draw do

  # Dynamic error pages
  get "/400", to: "errors#bad_request"
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  apipie
  namespace :api do
    namespace :v1 do
      resources :claps, only: [:create]
      resources :saved_routes, only: [:index, :create, :destroy]
      resources :routes do
        resources :point_of_interests, only: [:create, :destroy]
        post 'point_of_interests_many', to: 'point_of_interests#create_many'
        get :export_gpx_file
      end
      get 'search', to: 'search#search'
      get 'location_search', to: 'search#location_search'
      resources :sessions, only: [:create, :destroy]
      resources :registrations, only: [:create]
      resources :users do
        resources :followed_blogs, only: [:create, :destroy, :index]
      end
      resources :conversations do
        resources :messages, only: [:index, :create, :update]
      end
      resources :trips do
        resources :posts do
          resources :post_pictures, only: [:create, :destroy]
        end
        resources :donation_goals, only: [:create, :edit]
        resources :post_groups, only: [:show, :update]
        resources :gear_lists, only: [:create, :update]
        resources :transactions, only: [:create]
        resources :poly_line_strings, only: [:index]
      end
    end
  end

  devise_for :users, :controllers => { :registrations => 'registrations', omniauth_callbacks: 'api/v1/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get "/about", to: "home#about", as: "about"
  get "/terms", to: "home#terms", as: "terms"

  resources :feedbacks, only: [:create]

  resources :users do
    resources :followed_blogs, only: [:index, :create, :destroy]
    get "verification", to: "users#verification", as: "verification"
    get "unsubscribe", to: "users#unsubscribe", as: "unsubscribe"
    patch "pardon", to: "admin#pardon", as: "pardon"
    patch "warn", to: "admin#warn", as: "warn"
    patch "ban", to: "admin#ban", as: "ban"
  end

  # admin route
  resources :admin, only: [:index]
  get "/admin/flagged_messages", to: "admin#flagged_messages", as: "flagged_messages"

  get 'search', to: 'search#search'
  get :trip_planner_search, to: "search#location_search"

  resources :trips do
    get "track_route", to: "posts#track_route", as: "track_route"
    resources :posts do
      resources :post_pictures, only: [:new, :create, :destroy]
      get "fetch_images", to: "post_pictures#fetch_images", as: "fetch_images"
    end
    get :fetch_posts
    resources :transactions, only: [:new, :create]
    resources :donation_goals, only: [:new, :create, :update, :edit]
    resources :post_groups, only: [:show, :update]
    resources :gear_lists, only: [:create, :update]
    get "fetch_post/:id", to: "post_groups#fetch_post", as: "fetch_post"
    get "fetch_post_planer/:id", to: "trip_planner#fetch_post", as: "fetch_post_planer"
  end

  resources :claps, only: [:create]
  resources :comments, only: [:create, :update, :destroy]

  resources :routes do
    resources :point_of_interests, only: [:create, :destroy]
    get :fetch_pois
    get :export_gpx_file
  end
  resources :saved_routes, only: [:index, :create, :show, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @user_id = current_user.id
    end
    trips = Trip.all
    @featured_trips = []
    3.times do
      @featured_trips << trips.sample
    end
    @feedback = Feedback.new()
  end

  def about
    @feedback = Feedback.new()
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_route_explorer_modal.html.erb
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API'] %>&libraries=places,geometry">
</script>
<script type="text/javascript">
$(function(){
  function initialize() {

    var input1 = document.getElementById('start_route');
    var input2 = document.getElementById('end_route');
    var autocomplete1 = new google.maps.places.Autocomplete(input1);
    var autocomplete2 = new google.maps.places.Autocomplete(input2);
  }
  google.maps.event.addDomListener(window, 'load', initialize);
})
</script>

<div id="route_explorer_modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Chose Two Points</h4>
      </div>
      <div class="modal-body">
        <%= form_tag routes_path, method: "get" do |f| %>
          <%= label_tag :start, 'Starting Place' %>
          <%= text_field_tag :start_route, nil, :class => "form-control" %>
          <%= label_tag :end, 'Ending Place' %>
          <%= text_field_tag :end_route, nil, :class => "form-control" %>
      </div>
      <div class="modal-footer">
          <%= submit_tag "Submit", :class => "btn btn-submit" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_trip_explorer_modal.html.erb
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API'] %>&libraries=places,geometry">
</script>
<script type="text/javascript">
$(function(){
  function initialize() {

    var input1 = document.getElementById('start');
    var input2 = document.getElementById('end');
    var autocomplete1 = new google.maps.places.Autocomplete(input1);
    var autocomplete2 = new google.maps.places.Autocomplete(input2);
  }
  google.maps.event.addDomListener(window, 'load', initialize);
})
</script>

<div id="trip_explorer_modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Chose Two Points</h4>
      </div>
      <div class="modal-body">
        <%= form_for search_path, method: "get" do |f| %>
          <%= f.label :q, 'Name' %>
          <%= f.text_field :q, :class => "form-control" %>
          <%= f.label :start, 'Starting Place' %>
          <%= f.text_field :start, :class => "form-control" %>
          <%= f.label :end, 'Ending Place' %>
          <%= f.text_field :end, :class => "form-control" %>
      </div>
      <div class="modal-footer">
          <%= f.submit "Submit", :class => "btn btn-submit" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 title">
      <h1><%= t("about.site_title") %></h1>
      <p><%= t("about.site_text") %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h1><%= t("about.about_title") %></h1>
    </div>
    <div class="col-sm-3">
      <%= image_tag "about.JPG", :class=> "user-cover-photo img-rounded" %>
    </div>
    <div class="col-sm-9">
      <p><%= t("about.about_text_1") %><br>
        <br><%= t("about.about_text_2") %>
        <br><br>Please fill out the form below to contact me!
        <div class="about-feedback-box">
          <%= form_for @feedback do |f| %>
          <%= f.label :email, "Email" %>
          <%= f.text_field :email, required: true, autofocus: true, class: "form-control", placeholder: "my@email.com" %>
          <%= f.label :content, "Message" %>
          <%= f.text_area :content, required: true, autofocus: true, class: "form-control", placeholder: "Message content" %>
          <%= f.submit "Submit", :class => "btn btn-primary btn-xl" %>
          <% end %>
        </div>
      </p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div id="<%= css_slug %>">
  <header class="masthead">
    <div class="header-content">
      <div class="header-content-inner">
        <% if current_user %>
          <h1 id="homeHeading"><%= t("homepage.lander") %></h1>
          <hr>
          <p><%= t("homepage.lander_text") %></p>
          <div class="button-group">
            <button type="button" id="search-route-homepage" name="button" class="btn btn-primary btn-xl" data-toggle="modal" data-target="#route_explorer_modal"><%= t("homepage.go_to_page") %></button>
            <!-- <%# button_to(t("homepage.go_to_page"), user_path(@user_id), :class => 'btn btn-primary btn-xl ', :method => :get) %> -->
            <button type="button" id="search-trip-homepage" name="button" class="btn btn-primary btn-xl" data-toggle="modal" data-target="#trip_explorer_modal">Search Trips</button>
          </div>
        <% else %>
          <h1 id="homeHeading"><%= t("homepage.lander_not_logged") %></h1>
          <hr>
          <p><%= t("homepage.lander_text") %></p>
          <!-- <%# button_to('Sign Up Now', new_user_registration_path, :class => 'btn btn-warning btn-lg btn-secondary sharp', :method => :get) %> -->
          <div class="button-group">
            <%= button_to(t("homepage.sign_up_now"), new_user_registration_path, :class => 'btn btn-primary btn-xl', :method => :get) %>
            <button type="button" id="search-trip-homepage" name="button" class="btn btn-primary btn-xl" data-toggle="modal" data-target="#trip_explorer_modal">Search Trips</button>
          </div>
        <% end %>
      </div>
    </div>
  </header>
  <%= render "trip_explorer_modal" %>
  <%= render "route_explorer_modal" %>
  <% if @featured_trips.length > 0 %>
    <section class="bg-primary" id="about">
      <div class="container new-trips-container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h1><%= t('homepage.current_trips') %></h1>
            <div class="trip-carousel">
              <% @featured_trips.each_with_index do |trip, index| %>
                <% if trip != nil %>
                  <div class="trip-slider-<%= trip.id %> trip-slider" data-trip-id=<%= trip.id %>>
                    <% if trip.photo.url != nil %>
                      <style media="screen">
                        .trip-slider-<%= trip.id %> {
                          background-image: url(<%= trip.photo.url %>)
                        }
                      </style>
                    <% else %>
                    <style media="screen">
                      .trip-slider-<%= trip.id %> {
                        background-image: url(<%= asset_url("#{(index + 1).to_s}.jpg") %>)
                      }
                    </style>
                    <% end %>
                    <h2><a href="<%= trip_path(trip) %>" class="trip-link">View <%= trip.user.name %>'s Trip</a></h2>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </section>
  <% end %>

  <section id="services">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading"><%= t("homepage.support") %></h2>
          <hr class="primary">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <i class="fa fa-4x fa-bicycle text-primary sr-icons"></i>
            <h3><%= t("homepage.built_title") %></h3>
            <p class="text-muted"><%= t("homepage.built_text") %></p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <i class="fa fa-4x fa-usd text-primary sr-icons"></i>
            <h3><%= t("homepage.raise_title") %></h3>
            <p class="text-muted"><%= t("homepage.raise_text") %></p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <i class="fa fa-4x fa-map-marker text-primary sr-icons"></i>
            <h3><%= t("homepage.chart_title") %></h3>
            <p class="text-muted"><%= t("homepage.chart_text") %></p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <i class="fa fa-4x fa-envelope text-primary sr-icons"></i>
            <h3><%= t("homepage.connect_title") %></h3>
            <p class="text-muted"><%= t("homepage.connect_text") %></p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- <section class="p-0" id="portfolio">
    <div class="container-fluid">
      <div class="row no-gutter popup-gallery">
        <%# @featured_trips.each do |trip| %>
          <div class="col-lg-4 col-sm-6">
            <%# if trip.photo.url == nil %>
            <a class="portfolio-box" href="<%# trip_path(trip) %>">
              <%# image_tag "1.jpg", :class => "img-fluid" %>
            <%# else %>
            <a class="portfolio-box" href="<%# trip_path(trip) %>">
              <%# image_tag "1.jpg", :class => "img-fluid" %>
              <img class="img-fluid" src="<%# trip.photo.url %>" alt="">
            <%# end %>
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-name">
                    <%# trip.trip_name %>
                  </div>
                </div>
              </div>
            </a>
          </div>
        <%# end %>
      </div>
    </div>
  </section> -->

  <div class="call-to-action bg-dark">
    <div class="container text-center">
      <% if current_user %>
        <h2><%= t("homepage.go_to_page") %></h2>
        <%= link_to t("homepage.go_to_page"), user_path(@user_id), :class => 'btn btn-primary btn-xl' %>
      <% else %>
        <h2><%= t("homepage.sign_up_now") %></h2>
        <%= link_to t("homepage.sign_up_now"), new_user_registration_path, :class => 'btn btn-default btn-xl sr-button' %>
      <% end %>
    </div>
  </div>

  <section id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading"><%= t("homepage.feedback_title") %></h2>
          <hr class="primary">
          <p><%= t("homepage.feedback_text") %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12 mr-auto text-center">
          <i class="fa fa-envelope-o fa-3x sr-contact"></i>
          <div class="feedback-box">
            <%= form_for @feedback do |f| %>
            <%= f.label :email, "Email" %>
            <%= f.text_field :email, required: true, class: "form-control", placeholder: "my@email.com" %>
            <%= f.label :content, "Message" %>
            <%= f.text_area :content, required: true, class: "form-control", placeholder: "Message content" %>
            <%= f.submit "Submit", :class => "btn btn-primary btn-xl" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/home/terms.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Terms and Conditions</h1>
      <p>This Privacy Policy governs the manner in which Travel on Two collects, uses, maintains and discloses information collected from users (each, a "User") of the http://www.travelontwo.bike website ("Site").</p>
      <h3>Personal identification information</h3>
      <p>We may collect personal identification information from Users in a variety of ways, including, but not limited to, location information, when Users visit our site, register on the site, fill out a form, and in connection with other activities, services, features or resources we make available on our Site. Users may be asked for, as appropriate, name, email address, mailing address. Users may, however, visit our Site anonymously. We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain Site related activities.</p>
      <h3>Non-personal identification information</h3>
      <p>We may collect non-personal identification information about Users whenever they interact with our Site. Non-personal identification information may include the browser name, the type of computer and technical information about Users means of connection to our Site, such as the operating system and the Internet service providers utilized and other similar information.</p>
      <h3>Web browser cookies</h3>
      <p>Our Site may use "cookies" to enhance User experience. User's web browser places cookies on their hard drive for record-keeping purposes and sometimes to track information about them. User may choose to set their web browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly.</p>
      <h3>How we use collected information</h3>
      <p>Travel on Two may collect and use Users personal information for the following purposes:</p>
      <ul>
        <li>To run and operate our Site</li>
      </ul>
      <p>We may need your information display content on the Site correctly.</p>
      <ul>
        <li>To improve customer service</li>
      </ul>
      <p>Information you provide helps us respond to your customer service requests and support needs more efficiently.</p>
      <ul>
        <li>To personalize user experience</li>
      </ul>
      <p>We may use information in the aggregate to understand how our Users as a group use the services and resources provided on our Site.</p>
      <ul>
        <li>To improve our Site</li>
      </ul>
      <p>We may use feedback you provide to improve our products and services.</p>
      <ul>
        <li>To send periodic emails</li>
      </ul>
      <p>We may use the email address to send User information and updates pertaining to their order. It may also be used to respond to their inquiries, questions, and/or other requests.</p>
      <h3>How we protect your information</h3>
      <p>We adopt appropriate data collection, storage and processing practices and security measures to protect against unauthorized access, alteration, disclosure or destruction of your personal information, username, password, transaction information and data stored on our Site.</p>
      <h3>Sharing your personal information</h3>
      <p>We do not sell, trade, or rent Users personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates and advertisers for the purposes outlined above.</p>
      <h3>Electronic newsletters</h3>
      <p>If User decides to opt-in to our mailing list, they will receive emails that may include company news, updates, related product or service information, etc.</p>
      <h3>Changes to this privacy policy</h3>
      <p>Travel on Two has the discretion to update this privacy policy at any time. When we do, we will revise the updated date at the bottom of this page. We encourage Users to frequently check this page for any changes to stay informed about how we are helping to protect the personal information we collect. You acknowledge and agree that it is your responsibility to review this privacy policy periodically and become aware of modifications.</p>
      <h3>Your acceptance of these terms</h3>
      <p>By using this Site, you signify your acceptance of this policy. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes. This privacy policy was built using the generator at PrivacyPolicies.com.</p>
      <h3>Contacting us</h3>
      <p>If you have any questions about this Privacy Policy, the practices of this site, or your dealings with this site, please contact us.</p>
      <p>This document was last updated on April 07, 2018</p>
    </div>
  </div>
</div>