config/routes.rb
Rails.application.routes.draw do

  # Dynamic error pages
  get "/400", to: "errors#bad_request"
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  apipie
  namespace :api do
    namespace :v1 do
      resources :claps, only: [:create]
      resources :saved_routes, only: [:index, :create, :destroy]
      resources :routes do
        resources :point_of_interests, only: [:create, :destroy]
        post 'point_of_interests_many', to: 'point_of_interests#create_many'
        get :export_gpx_file
      end
      get 'search', to: 'search#search'
      get 'location_search', to: 'search#location_search'
      resources :sessions, only: [:create, :destroy]
      resources :registrations, only: [:create]
      resources :users do
        resources :followed_blogs, only: [:create, :destroy, :index]
      end
      resources :conversations do
        resources :messages, only: [:index, :create, :update]
      end
      resources :trips do
        resources :posts do
          resources :post_pictures, only: [:create, :destroy]
        end
        resources :donation_goals, only: [:create, :edit]
        resources :post_groups, only: [:show, :update]
        resources :gear_lists, only: [:create, :update]
        resources :transactions, only: [:create]
        resources :poly_line_strings, only: [:index]
      end
    end
  end

  devise_for :users, :controllers => { :registrations => 'registrations', omniauth_callbacks: 'api/v1/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get "/about", to: "home#about", as: "about"
  get "/terms", to: "home#terms", as: "terms"

  resources :feedbacks, only: [:create]

  resources :users do
    resources :followed_blogs, only: [:index, :create, :destroy]
    get "verification", to: "users#verification", as: "verification"
    get "unsubscribe", to: "users#unsubscribe", as: "unsubscribe"
    patch "pardon", to: "admin#pardon", as: "pardon"
    patch "warn", to: "admin#warn", as: "warn"
    patch "ban", to: "admin#ban", as: "ban"
  end

  # admin route
  resources :admin, only: [:index]
  get "/admin/flagged_messages", to: "admin#flagged_messages", as: "flagged_messages"

  get 'search', to: 'search#search'
  get :trip_planner_search, to: "search#location_search"

  resources :trips do
    get "track_route", to: "posts#track_route", as: "track_route"
    resources :posts do
      resources :post_pictures, only: [:new, :create, :destroy]
      get "fetch_images", to: "post_pictures#fetch_images", as: "fetch_images"
    end
    get :fetch_posts
    resources :transactions, only: [:new, :create]
    resources :donation_goals, only: [:new, :create, :update, :edit]
    resources :post_groups, only: [:show, :update]
    resources :gear_lists, only: [:create, :update]
    get "fetch_post/:id", to: "post_groups#fetch_post", as: "fetch_post"
    get "fetch_post_planer/:id", to: "trip_planner#fetch_post", as: "fetch_post_planer"
  end

  resources :claps, only: [:create]
  resources :comments, only: [:create, :update, :destroy]

  resources :routes do
    resources :point_of_interests, only: [:create, :destroy]
    get :fetch_pois
    get :export_gpx_file
  end
  resources :saved_routes, only: [:index, :create, :show, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/models/post_group.rb
class PostGroup < ApplicationRecord
  has_many :posts
  belongs_to :trip

  mount_uploader :image, PostGroupUploader
end

app/controllers/api/v1/post_groups_controller.rb
class Api::V1::PostGroupsController < Api::V1::BaseController

  api :get, "trips/:trip_id/post_groups/:id"
  def show
    @current_user = User.find(params[:user_id])
    post_group = PostGroup.find(params[:id])
    result = PostGroupSerializer.new(post_group)
    result.object.posts.each do |post|
      already_clapped = already_clapped?(post)
      post.already_clapped = already_clapped
    end
    json_result = JSON.parse({ post_group: result }.to_json)
    json_result["post_group"]["posts"].each do |post_hash|
      post = Post.find(post_hash["id"])
      route = post.route
      clapped = already_clapped?(post)
      post_hash["already_clapped"] = clapped
      post_hash["route"] = route
    end
    render(json: json_result.to_json )
  end


  api :put, "trips/:trip_id/post_groups/:id"
  def update
    @post_group = PostGroup.find(params[:id])
    @post_group.image = params[:file]
    if @post_group.save
      render(json: {:success => true, :trip => @post_group}.to_json)
    else
      render(json: {:success => "error"}.to_json)
    end
  end

  private
  def already_clapped?(post)
    check = false
    @current_user.claps.each do |clap|
      if clap.post_id == post.id
        check = true
      end
    end
    return check
  end

end

app/controllers/post_groups_controller.rb
class PostGroupsController < ApplicationController
  before_action :load_trip
  before_filter :require_permission, only: :update


  def show
    @trip = Trip.find(params[:trip_id])
    @post_group = PostGroup.find(params[:id])
    @posts = @post_group.posts.sort_by {|obj| obj.day}
    @post = @posts.first
    @route = @post.route
    @post_pictures = @post.post_pictures
    @user = @trip.user
    @max_post_group = max_post_group(@trip, @post_group)
    @min_post_group = min_post_group(@trip, @post_group)
    @claps = @post.claps.length
    @new_clap = Clap.new()
    if @current_user != nil
      @already_clapped = already_clapped?(@post)
    end
  end

  def update
    @post_group = PostGroup.find(params[:id])
    if @post_group.update_attributes(post_group_params)
      redirect_to trip_path(@trip)
    else
      flash[:error] = "Something went wrong"
      redirect_to trip_path(@trip)
    end
  end

  def fetch_post
    @post = Post.find(params[:id])
    @post_pictures = @post.post_pictures
    @user = current_user
    @route = @post.route
    @claps = @post.claps.length
    @new_clap = Clap.new()
    @already_clapped = already_clapped?(@post)
    respond_to do |format|
      format.js
    end
  end

  private
  def load_trip
    @trip = Trip.find(params[:trip_id])
  end

  def post_group_params
    params.require(:post_group).permit(:month, :year, :image)
  end

  def already_clapped?(post)
    check = false
    @current_user.claps.each do |clap|
      if clap.post_id == post.id
        check = true
      end
    end
    return check
  end

  def max_post_group(trip, post_group)
    post_groups = trip.post_groups.sort_by {|obj| Date::MONTHNAMES.index(obj.month) && obj.year.to_i }
    index = post_groups.find_index(post_group)
    if index == post_groups.length
      return nil
    elsif post_groups == []
      return nil
    else
      max_post_group = post_groups[index+1]
      return max_post_group
    end
  end

  def min_post_group(trip, post_group)
    post_groups = trip.post_groups.sort_by {|obj| Date::MONTHNAMES.index(obj.month) && obj.year.to_i }
    index = post_groups.find_index(post_group)
    if index == 0
      return nil
    elsif post_groups == []
      return nil
    else
      min_post_group = post_groups[index-1]
      return min_post_group
    end
  end

  def require_permission
    if current_user != Trip.find(params[:trip_id]).user
      redirect_to root_path
    end
  end

end

app/helpers/post_groups_helper.rb
module PostGroupsHelper
end

app/views/post_groups/_post.html.erb
<script type="text/javascript">
$( document ).ready(function() {

  $(".center").slick({
    slidesToShow: 3,
    arrows: true,
    responsive: [
           {
             breakpoint: 1280,
             settings: {
               slidesToShow: 2,
               slidesToScroll: 1
             }
           },
           {
             breakpoint: 1000,
             settings: {
               slidesToShow: 1,
               slidesToScroll: 1
             }
           }
         ]
  });


  $("#new_clap").on("submit",function(e){
    e.preventDefault()
    $.ajax({
      method: 'post',
      url: '/claps',
      data: $("#new_clap").serialize(),
      dataType: 'json'
    }).done(function(msg){
      var count = parseInt($("#claps-count").html()) + 1
      $("#claps-count").html(count.toString())
    }).fail(function(msg){
      alert('Sorry stuff went wrong')
    });
  })


})
</script>

<%= hidden_field_tag 'current_post_date', "#{@post.id}" %>
<div class="post-title">
  <h1><%= @post.post_title.upcase %></h1>
</div>
<% if current_user == @user %>
  <%= link_to "Edit Post", edit_trip_post_url(@post.trip, @post) %>
<% end %>
<% if @route %>
  <div class="post-details row">
    <div class="col-sm-4">
      <p>
        <%= @post.trip.user.name %>
      </p>
    </div>
    <div class="col-sm-4">
      <p>
        <%= @route.address1 %> to <%= @route.address2 %>
      </p>
    </div>
    <% unless @route.distance == nil %>
      <div class="col-sm-4">
        <p>
          Total Distance: <%= @route.distance %> km
        </p>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="post-details row">
    <div class="col-sm-12">
      <p>
        <%= @post.trip.user.name %>
      </p>
    </div>
  </div>
<% end %>
<div class="row post-text-row">
  <div class="col-sm-12">
    <p>
      <%= simple_format(@post.post_content) %>
    </p>
  </div>
</div>
<% unless @post.post_pictures == nil %>
  <section class="center slider">
    <% @post.post_pictures.each_with_index do |post_picture, index| %>
      <div class="post-picture-image">
        <%= image_tag(post_picture.picture_url, class: "post-picture", 'data-target': "##{post_picture.id}", 'data-toggle': "modal") if post_picture.picture? %>
      </div>
    <% end %>
  </section>
  <% @post.post_pictures.each_with_index do |post_picture, index| %>
    <div id="<%= post_picture.id %>" class="modal fade" role="dialog">
      <div class="modal-dialog modal-lg"> -->
        <div class="modal-content">
          <div class="modal-body">
            <div class="modal-body-image">
              <%= image_tag(post_picture.picture_url, class: "post-picture-modal") if post_picture.picture? %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>

      </div>
    </div>
  <% end %>
<% end %>
<div class="comments-claps row">
    <div class="col-sm-12 claps-col">
      <p id="claps-count"><%= @claps %></p>
      <% if @already_clapped == true || @already_clapped == nil %>
        <%= image_tag asset_url("icons/clap-hands.png") %>
        <button type="button" name="button" class="btn btn-primary" disabled>Add Clap</button>
      <% else %>
        <%= form_for @new_clap do |f| %>
          <%= hidden_field_tag :post_id, @post.id %>
          <%= image_tag asset_url("icons/clap-hands.png"), :id => "clap-hand-img-good" %>
          <%= f.submit "Add Clap", :class => "btn btn-primary", :id => "add-clap-button" %>
        <% end %>
      <% end %>
    </div>
</div>

app/views/post_groups/fetch_post.js.erb
$("#post-container").html('<%= escape_javascript(render :partial => "post", :locals => { :post => @post, :post_pictures => @post_pictures, :user => @user, :route => @route, :claps => @claps, :new_clap => @new_clap}) %>');

app/views/post_groups/show.html.erb
<script
 src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API'] %>&libraries=geometry">
</script>
<%= javascript_include_tag "trip_planner" %>
<%= hidden_field_tag "trip_id", @trip.id %>
<div id="wrapper">
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand"><a href="<%= trip_path(@trip) %>">Back to trip</a></li>
      <% @posts.each_with_index do |post, index| %>
        <% if index == 0 %>
          <% if post.route %>
            <li class="<%="#{post.id}" %> sidebar-active-item"><a href="<%= trip_fetch_post_url(@trip, post) %>" class="post-sidebar-item trip-planner-sidebar-item" data-value="<%= post.id %>" data-lat="<%= post.route.center_lat %>" data-lng="<%= post.route.center_lng %>"><%= "#{post.post_group.month} #{post.day}" %></a></li>
          <% else %>
            <li class="<%="#{post.id}" %> sidebar-active-item"><a href="<%= trip_fetch_post_url(@trip, post) %>" class="post-sidebar-item trip-planner-sidebar-item" data-value="<%= post.id %>"><%= "#{post.post_group.month} #{post.day}" %></a></li>
          <% end %>
        <% else %>
          <% if post.route %>
            <li class="<%= post.id %>"><a href="<%= trip_fetch_post_url(@trip, post) %>" class="post-sidebar-item trip-planner-sidebar-item" data-value="<%= post.id %>" data-lat="<%= post.route.center_lat %>" data-lng="<%= post.route.center_lng %>"><%= "#{post.post_group.month} #{post.day}" %></a></li>
          <% else %>
            <li class="<%="#{post.id}" %> sidebar-active-item"><a href="<%= trip_fetch_post_url(@trip, post) %>" class="post-sidebar-item trip-planner-sidebar-item" data-value="<%= post.id %>"><%= "#{post.post_group.month} #{post.day}" %></a></li>
          <% end %>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row post-group-row">
        <div class="col-lg-12">
          <a href="#menu-toggle" class="btn btn-primary" id="menu-toggle"><span class="glyphicon glyphicon-calendar"></span> Change Date</a>
          <div class="align-left-button">
            <% unless @min_post_group == nil %>
              <%= button_to "Back to #{@min_post_group.month}", trip_post_group_path(@trip, @min_post_group), :class => "btn btn-primary sharp", :method => :get %>
            <% end %>
          </div>
          <div class="align-right-button">
            <% unless @max_post_group == nil %>
              <%= button_to "Next to #{@max_post_group.month}", trip_post_group_path(@trip, @max_post_group), :class => "btn btn-primary sharp", :method => :get %>
            <% end %>
          </div>
          <%= link_to "Back to Trip", trip_path(@trip), :class => "back-to-trip-link" %>
          <div id="map-trip-planner">

          </div>
          <div id="post-container">
            <%= render 'post' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>